version: '3.9'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080" # Maps local port 5000 to container port 8080
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app # Optional: Mount local directory for live code changes
